export let txt_available_power = `available power`;
export let txt_back = `back`;
export let txt_buy = `buy`;
export let txt_cr = `cr`;
export let txt_credits = `credits`;
export let txt_empty_string = ``;
export let txt_engines = "engines";
export let txt_exit_system = `exit system`;
export let txt_hull = `hull`;
export let txt_install = `install`;
export let txt_kb = `kb`;
export let txt_kg = `kg`;
export let txt_leave = `leave`;
export let txt_m_lasers = "m.lasers";
export let txt_menu = `menu`;
export let txt_planet = `planet`;
export let txt_raw_materials = `raw materials`;
export let txt_repair = `repair`;
export let txt_research_data = `research data`;
export let txt_save_and_quit = `save and quit`;
export let txt_scanners = "scanners";
export let txt_sell = `sell`;
export let txt_shields = `shields`;
export let txt_star = `star`;
export let txt_station = `station`;
export let txt_systems = `systems`;
export let txt_toggle = `toggle`;
export let txt_upgrade = `upgrade`;
export let txt_weapons = "weapons";


export let txt_buy_raw_materials = `${ txt_buy } ${ txt_raw_materials } 100${ txt_cr } = 25${ txt_kg }`;
export let txt_hull_repair_cost = `50${ txt_cr }`;
export let txt_not_installed = `not ${ txt_install }ed`;
export let txt_planet_gas = `gas ${ txt_planet }`;
export let txt_planet_rock = `rocky ${ txt_planet }`;
export let txt_repair_hull = `${ txt_repair } ${ txt_hull }`;
export let txt_sell_raw_materials = `${ txt_sell } ${ txt_raw_materials } 25${ txt_kg } = 75${ txt_cr }`;
export let txt_sell_research = `${ txt_sell } ${ txt_research_data } 32${ txt_kb } = 100${ txt_cr }`;
export let txt_toggle_fullscreen = `${ txt_toggle } fullscreen`;
export let txt_toggle_music = `${ txt_toggle } music`;
export let txt_upgrade_hull = `${ txt_upgrade } ${ txt_hull }`;
export let txt_upgraded_fully = `fully ${ txt_upgrade }d`;
export let txt_visit_station = `visit ${ txt_station }`;