#  Name of workflow
name: Deploy To Netlify

# When workflow is triggered
on:
  push:
    branches: [ main ]

# Jobs to carry out
jobs:
  deploy:
    # Operating system to run job on
    runs-on: windows-latest
    env:
      NODE_ENV: production
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    # Steps in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.14'
          cache: 'yarn'
            
      - name: Setup Environment
        run: yarn install
        
      - name: Build and Zip the Game
        run: yarn release:netlify

      - name: Deploy to netlify
        run: yarn deploy:netlify
