#  Name of workflow
name: Deploy To Netlify

# When workflow is triggered
on:
  push:
    branches: [ main ]

# Jobs to carry out
jobs:
  deploy:
    # Operating system to run job on
    runs-on: windows-latest
    env:
      NODE_ENV: production
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1

      # Run npm install and build on our code
      - name: Setup Environment
        run: yarn install
        
      - name: Build and Zip the Game
        run: yarn netlify

      # Deploy to Netlify using our production secrets
      - name: Deploy to netlify
        run: ./node_modules/.bin/netlify deploy --dir=dist/src --prod
